install:
	defaults write com.apple.dt.Xcode DVTTextEditorTrimTrailingWhitespace -bool true
	defaults write com.apple.dt.Xcode DVTTextEditorTrimWhitespaceOnlyLines -bool true
	defaults write com.apple.dt.Xcode DVTTextEditorWrapsLines -bool false
	defaults write com.apple.dt.Xcode DVTTextPageGuideLocation -int 100
	defaults write com.apple.dt.Xcode DVTTextShowLineNumbers -bool false
	defaults write com.apple.dt.Xcode DVTTextShowPageGuide -bool true
	defaults write com.apple.dt.Xcode IDEIndexerActivityShowNumericProgress -bool true
	defaults write com.apple.dt.Xcode IDEKeyBindingCurrentPreferenceSet -string max.idekeybindings
	defaults write com.apple.dt.Xcode ShowBuildOperationDuration -bool true
